apiVersion: v1
kind: ConfigMap

metadata:

  name: grafana-datasource

  namespace: sre-demo


data:

  datasource.yaml: |

    apiVersion: 1


    datasources:


    - name: Prometheus

      type: prometheus

      access: proxy

      url: http://prometheus:9090

      isDefault: true

      editable: true



---

apiVersion: v1
kind: PersistentVolumeClaim

metadata:

  name: grafana-storage

  namespace: sre-demo


spec:


  accessModes:

  - ReadWriteOnce


  resources:


    requests:


      storage: 5Gi



---

apiVersion: apps/v1
kind: Deployment


metadata:


  name: grafana


  namespace: sre-demo


  labels:


    app: grafana



spec:


  replicas: 1


  selector:


    matchLabels:


      app: grafana



  template:


    metadata:


      labels:


        app: grafana



    spec:


      # Fix Azure disk permission issue

      securityContext:


        fsGroup: 472



      # Fix existing volume ownership

      initContainers:


      - name: grafana-permission-fix


        image: busybox:1.36


        command:


        - sh


        - -c


        - |


          chown -R 472:472 /var/lib/grafana



        volumeMounts:


        - name: grafana-storage


          mountPath: /var/lib/grafana



      containers:


      - name: grafana


        image: grafana/grafana:11.3.0


        name: grafana



        ports:


        - containerPort: 3000



        env:


        - name: GF_SECURITY_ADMIN_USER


          value: admin



        - name: GF_SECURITY_ADMIN_PASSWORD


          value: admin123



        - name: GF_USERS_ALLOW_SIGN_UP


          value: "false"



        volumeMounts:



        - name: grafana-storage


          mountPath: /var/lib/grafana



        - name: grafana-datasource


          mountPath: /etc/grafana/provisioning/datasources



      volumes:



      - name: grafana-storage


        persistentVolumeClaim:


          claimName: grafana-storage



      - name: grafana-datasource


        configMap:


          name: grafana-datasource




---

apiVersion: v1
kind: Service


metadata:


  name: grafana


  namespace: sre-demo



  labels:


    app: grafana



spec:


  type: LoadBalancer



  selector:


    app: grafana



  ports:



  - name: http


    port: 3000


    targetPort: 3000
